#!/usr/bin/env bash
# Stamp a freshly built bundle with the identity of the flavor it was compiled
# as, and rename it to match.
#
#   ./scripts/brand.sh release
#   ./scripts/brand.sh dev
#
# Run by `make build` straight after `wails build`. Wails renders Info.plist from
# build/darwin/Info.plist with a hardcoded bundle identifier and takes the name
# from wails.json, neither of which knows about flavors — so the two values that
# make macOS treat the dev app as a *different application* are set here.
#
# The values come from the binary itself (`petd --flavor`), not from this script.
# internal/flavor is the only place they exist, and asking the binary also proves
# the -ldflags stamp actually took effect: a release binary in a bundle you asked
# to be dev is caught here rather than at the point where two apps quietly share
# a port and a data directory.
set -euo pipefail

WANT=${1:-release}
case $WANT in
release | dev) ;;
*) echo "usage: brand.sh [release|dev]" >&2; exit 2 ;;
esac

die() { echo "error: $*" >&2; exit 1; }

# The bundle wails just wrote, named from wails.json — not "the only .app in
# build/bin". Both flavors can be sitting there at once, and `wails build -clean`
# only cleans its own output, so picking by wildcard brands whichever the
# filesystem happens to list first. That silently produced a stale dev app that
# looked freshly built.
WAILS_NAME=$(python3 -c "import json; print(json.load(open('wails.json'))['name'])")
APP="build/bin/$WAILS_NAME.app"
[ -d "$APP" ] || die "no bundle at $APP — wails build did not produce one

  A failed build leaves the previous bundle in place, so check the build said
  \"Built '...'\" before believing anything here."

FLAVOR_JSON=$("$APP/Contents/MacOS/petd" --flavor)
field() {
	printf '%s' "$FLAVOR_JSON" |
		python3 -c "import json,sys; print(json.load(sys.stdin)['$1'])"
}
ID=$(field id)
SLUG=$(field slug)
APP_NAME=$(field app_name)
BUNDLE=$(field bundle_id)

[ "$ID" = "$WANT" ] ||
	die "the built binary is stamped '$ID' but you asked for '$WANT'.

  The -ldflags stamp did not take effect. Building without it would produce a
  second app wearing the first one's port, config and data directory."

PLIST="$APP/Contents/Info.plist"
set_plist() { # key value
	/usr/libexec/PlistBuddy -c "Set :$1 $2" "$PLIST" 2>/dev/null ||
		/usr/libexec/PlistBuddy -c "Add :$1 string $2" "$PLIST"
}
# The version comes from the -ldflags stamp, not from wails.json. Both apps are
# built from one commit at two different versions, and wails.json holds one —
# so the bundle is made to agree with the binary inside it rather than with a
# file that cannot describe both.
VERSION=$(field version)
if [ "$VERSION" != dev ]; then
	set_plist CFBundleShortVersionString "$VERSION"
	set_plist CFBundleVersion "$VERSION"
fi

set_plist CFBundleIdentifier "$BUNDLE"
set_plist CFBundleName "$APP_NAME"
set_plist CFBundleDisplayName "$APP_NAME"

# The dev app gets its own Finder icon, built here from the committed PNG with
# sips and iconutil — both ship with macOS, so building needs no Pillow. The
# PNG itself is generated by scripts/gen-appicon-dev.py and committed.
if [ "$ID" = dev ] && [ -f build/appicon-dev.png ]; then
	work=$(mktemp -d)
	trap 'rm -rf "$work"' EXIT
	set=$work/icon.iconset
	mkdir -p "$set"
	for sz in 16 32 128 256 512; do
		sips -z $sz $sz build/appicon-dev.png --out "$set/icon_${sz}x${sz}.png" >/dev/null
		sips -z $((sz * 2)) $((sz * 2)) build/appicon-dev.png \
			--out "$set/icon_${sz}x${sz}@2x.png" >/dev/null
	done
	iconutil -c icns "$set" -o "$work/iconfile.icns"
	cp "$work/iconfile.icns" "$APP/Contents/Resources/iconfile.icns"
fi

DEST="build/bin/$SLUG.app"
if [ "$APP" != "$DEST" ]; then
	rm -rf "$DEST"
	mv "$APP" "$DEST"
fi

echo "branded $DEST  ($BUNDLE, \"$APP_NAME\", $VERSION)"
